spring:
  datasource:
    names: primary,replica0,replica1
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3316/dynamic_demo?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        pool-name: HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: select 1
    replica0:
      jdbc-url: jdbc:mysql://127.0.0.1:3326/dynamic_demo?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        pool-name: HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: select 1
    replica1:
      jdbc-url: jdbc:mysql://127.0.0.1:3326/dynamic_demo?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        pool-name: HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: select 1
    rule:
      primary-datasource-name: primary
      replica-datasource-name: replica0,replica1